// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Floss.App.Native
{
    internal static unsafe partial class FlossCompositeNativeMethods
    {
        const string __DllName = "floss_composite";

        internal const uint FLOSS_COMPOSITE_VERSION = 1;




        /// <summary>
        ///  Returns ABI version — bump when FFI signatures change.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "floss_composite_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint floss_composite_version();

        /// <summary>
        ///  Normal-blend `width` contiguous BGRA pixels from `src` onto `dst`.
        ///
        ///  # Safety
        ///  `dst` and `src` must point to at least `width * 4` valid bytes.
        ///  `opacity` is 0–255 (255 = full layer opacity).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "floss_composite_normal_row", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void floss_composite_normal_row(byte* dst, byte* src, int width, uint opacity);

        /// <summary>
        ///  Normal-blend a BGRA rectangle with independent row strides (bytes).
        ///
        ///  # Safety
        ///  `dst` must span `height` rows of `dst_stride` bytes; `src` must span
        ///  `height` rows of `src_stride` bytes; each row holds `width` pixels.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "floss_composite_normal_bgra_region", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void floss_composite_normal_bgra_region(byte* dst, int dst_stride, byte* src, int src_stride, int width, int height, uint opacity);

        /// <summary>
        ///  Fill a BGRA rectangle with `clear_value` (0xAABBGGRR little-endian).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "floss_clear_bgra_region", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void floss_clear_bgra_region(byte* dst, int dst_stride, int width, int height, uint clear_value);


    }



}
